CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TYPE "UserStatus" AS ENUM (
  'online',
  'away',
  'do_not_disturb',
  'hidden'
);

CREATE TABLE "User" (
  "id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  "username" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL,
  "email" varchar UNIQUE,
  "displayName" varchar,
  "avatarUrl" varchar,
  "status" "UserStatus" DEFAULT 'online',
  "statusMessage" varchar,
  "lastSeen" timestamp,
  "createdAt" timestamp DEFAULT (now()),
  "updatedAt" timestamp DEFAULT (now())
);

CREATE TABLE "RefreshToken" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "token" varchar UNIQUE NOT NULL,
  "userId" UUID NOT NULL,
  "createdAt" timestamp DEFAULT (now())
);

CREATE TABLE "Group" (
  "id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  "name" varchar NOT NULL,
  "isPrivateChat" boolean,
  "avatarUrl" varchar
);

CREATE TABLE "UserGroup" (
  "userID" UUID NOT NULL,
  "groupID" UUID NOT NULL,
  PRIMARY KEY ("userID", "groupID")
);

CREATE TABLE "Message" (
  "id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  "senderID" UUID NOT NULL,
  "groupID" UUID NOT NULL,
  "content" text NOT NULL,
  "createdAt" timestamp DEFAULT (now())
);

CREATE TABLE "Log" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "method" varchar NOT NULL,
  "url" varchar NOT NULL,
  "status" INT,
  "responseTime" INT,
  "userAgent" varchar,
  "ipAddress" varchar,
  "userID" UUID,
  "createdAt" timestamp DEFAULT (now())
);

ALTER TABLE "RefreshToken" ADD FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE;

ALTER TABLE "UserGroup" ADD FOREIGN KEY ("userID") REFERENCES "User" ("id") ON DELETE CASCADE;

ALTER TABLE "UserGroup" ADD FOREIGN KEY ("groupID") REFERENCES "Group" ("id") ON DELETE CASCADE;

ALTER TABLE "Message" ADD FOREIGN KEY ("senderID") REFERENCES "User" ("id") ON DELETE CASCADE;

ALTER TABLE "Message" ADD FOREIGN KEY ("groupID") REFERENCES "Group" ("id") ON DELETE CASCADE;

ALTER TABLE "Log" ADD FOREIGN KEY ("userID") REFERENCES "User" ("id") ON DELETE SET NULL;