CREATE TYPE "UserStatus" AS ENUM (
  'online',
  'away',
  'do_not_disturb',
  'hidden'
);

CREATE TABLE "User" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL,
  "email" varchar UNIQUE,
  "displayName" varchar,
  "avatarUrl" varchar,
  "status" "UserStatus" DEFAULT 'online',
  "statusMessage" varchar,
  "lastSeen" timestamp,
  "createdAt" timestamp DEFAULT (now()),
  "updatedAt" timestamp DEFAULT (now())
);

CREATE TABLE "RefreshToken" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "token" varchar UNIQUE NOT NULL,
  "userId" int NOT NULL,
  "createdAt" timestamp DEFAULT (now())
);

CREATE TABLE "Group" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "isPrivateChat" boolean,
  "avatarUrl" varchar
);

CREATE TABLE "UserGroup" (
  "userID" int NOT NULL,
  "groupID" int NOT NULL,
  PRIMARY KEY ("userID", "groupID")
);

CREATE TABLE "Message" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "senderID" int NOT NULL,
  "groupID" int NOT NULL,
  "content" text NOT NULL,
  "createdAt" timestamp DEFAULT (now())
);

CREATE TABLE "Log" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "method" varchar NOT NULL,
  "url" varchar NOT NULL,
  "status" INT,
  "responseTime" INT,
  "userAgent" varchar,
  "ipAddress" varchar,
  "userID" int,
  "createdAt" timestamp DEFAULT (now())
);

ALTER TABLE "RefreshToken" ADD FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE;

ALTER TABLE "UserGroup" ADD FOREIGN KEY ("userID") REFERENCES "User" ("id");

ALTER TABLE "UserGroup" ADD FOREIGN KEY ("groupID") REFERENCES "Group" ("id");

ALTER TABLE "Message" ADD FOREIGN KEY ("senderID") REFERENCES "User" ("id");

ALTER TABLE "Message" ADD FOREIGN KEY ("groupID") REFERENCES "Group" ("id");

ALTER TABLE "Log" ADD FOREIGN KEY ("userID") REFERENCES "User" ("id");